[tool.poetry]
name = "configula"
version = "0.3.1"
description = "Merges configuration from toml file and environment variables"
authors = ["Eugen Ciur <eugen@papermerge.com>"]

[tool.poetry.dependencies]
python = "^3.8"
tomlkit = "^0.7.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
