[tool.poetry]
name = "aws-lambda-utils-python"
version = "2.0.0"
description = ""
authors = ["nichmorgan-loft <nich.morgan@loft.com.br>"]
packages = [{ include = "aws_lambda_utils" }]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.20.7"
pydantic = "^1.8.2"
boto3-stubs = { extras = ["essential", "sns"], version = "^1.20.8" }

[tool.poetry.dev-dependencies]
black = "^21.11b0"
pytest = "^6.2.5"
flake8 = "^4.0.1"
pytest-envvars = "^1.2.1"
pytest-cov = "^3.0.0"
mypy = "^0.910"

[tool.pytest.ini_options]
testpaths = "tests"
addopts = "-vv --cov-report=term-missing --cov=aws_lambda_utils"
pytestenvvars__env_files = [".test.env"]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
exclude = "tests/"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
