[tool.poetry]
name = "leveldb-export"
version = "0.1.0"
description = "Package to export documents from LevelDB export (for instance Firestore)."
authors = ["JoÃ«l Luijmes <me@joell.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
appengine-python-standard = "^0.3.1"
protobuf = "^3.15.8"
google-crc32c = "^1.1.2"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
