[tool.poetry]
name = "aidkit-client"
version = "0.1.0"
description="aidkit for your CI/CD and j-notebooks."
authors = ["neurocat GmbH"]
readme = "README_PYPI.md"
license = "Apache-2.0"

packages = [
    {include = "aidkit_client"},
]

[tool.poetry.dependencies]
python = "~3.8.0"
httpx = "^0.21.1"
tensorflow = {version = "^2.7.0", optional = true}
tabulate = "^0.8.9"


[tool.poetry.dev-dependencies]
datamodel-code-generator = "^0.11.15"
types-tabulate = "^0.8.3"
pylint = "^2.12.1"
mypy = "^0.910"
flake8 = "^4.0.1"
twine = "^3.7.0"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
