[tool.poetry]
name = "fellipems_csv_json_converter"
version = "0.1.6"
description = "Curso de introducao ao python: Conversor CSV-JSON"
authors = ["FellipeMS <fellipems.sc@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.3"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"
mypy = "^0.910"
black = "^21.9b0"
isort = "^5.9.3"
pandas-stubs = "^1.2.0"
ipython = "^7.28.0"

[tool.poetry.scripts]
csv_converter = 'fellipems_csv_json_converter.converter:Converte_JSONCSV'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
