[tool.poetry]
name = "cocktail_info"
version = "0.1.3"
description = "Get the information of cocktails."
authors = ["Kun Yao"]
license = "MIT"
readme = "README.md"
documentation = 'https://cocktail_info.readthedocs.io'
homepage = "https://github.com/Kenyaokun/cocktail_info"
repository = "https://github.com/Kenyaokun/cocktail_info"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "1.3.4"
requests = "^2.26.0"
ipython = "7.29.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
myst-nb = "^0.13.1"
sphinx-autoapi = "^1.8.4"
sphinx-rtd-theme = "^1.0.0"
Sphinx = "^4.3.1"
sphinxcontrib-napoleon = "^0.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
