[tool.poetry]
name = "django-openid-connect"
version = "1.1.0-rc3"
description = "Django library providing OpenID Connect auth backend"
authors = ["Miroslav Bauer <bauer@cesnet.cz>"]

[tool.poetry.dependencies]
python = "^3.6"
django-rest-framework-social-oauth2 = "1.1.0"
urnparse = "0.2.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
