[tool.poetry]
name = "tictactoe_marlene"
version = "0.1.4"
description = "Tic Tac Toe game made with Python and Curses"
authors = ["Marlene Nunes"]
# provide packages from src directory
packages = [
    { include = "logic", from= "src"},
    { include = "cursesUI", from="src" },
]

[tool.poetry.dependencies]
python = "^3.8.10"
certifi = "2021.10.8"
pip = "21.2.4"
setuptools = "58.0.4"
wheel = "0.37.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

