[tool.poetry]
name = "pyemr"
version = "0.1.5"
description = "A lightweight package for running poetry projects on emr."
authors = ["Richard Brooker <richjbrooker@gmail.com>"]
packages = [
    { include = "pyemr"},
    { include = "**/*"},
]

include = [ "**/*.sh" ]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
fire = "^0.4.0"
sh = "^1.14.2"
tomlkit = "0.7.2"
awswrangler = "^2.13.0"
poetry = "^1.1.12"
pandas = "^1.3.5"
boto3 = "^1.20.23"
tqdm = "^4.62.3"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pyemr = "pyemr.cli:main"
