[tool.poetry]
name = "patric_converte"
version = "0.1.6"
description = ""
authors = ["Patric Rocha <patric_rocha@hotmail.com>"]


[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"
flake8 = "^4.0.1"
mypy = "^0.910"
black = "^21.12b0"
isort = "^5.10.1"
ipython = "^7.30.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
csv_converter = 'patric_converte.converter:conversor_de_csv_para_json'
json_converter = 'patric_converte.converter:conversor_de_json_para_csv'